pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('python/simple-math-uv') {
                    sh '/root/.local/bin/uv build'
                }
            }
        }
    }
}