pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile.build'
            dir 'python/simple-math-uv'
        }
    }
    environment {
        UV_CACHE_DIR = "${WORKSPACE}/.uv-cache"
    }
    stages {
        stage('Test and Build') {
            steps {
                dir('python/simple-math-uv') {
                    sh 'uv run pytest'
                    sh 'uv build'
                }
            }
        }
    }
}